### ISSUE TITLE
Rework README

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#1001]
Right now the README for this project has a mix of too much detailed information and not enough pointers to the actual docs. We should make a pass at cleaning this up and updating it to play nicely with our main docs.

**Comment by Ian2012** [comment]
Hey  @that-ar-guy feel free to start working on it

**Comment by bmtcril** [comment]
@that-ar-guy Sure! Have you signed a contributor agreement for Open edX yet? https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+Start+Contributing+Code
