### ISSUE TITLE
Change XAPI database

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#126]
There is a setting to update the XAPI database however, this setting is not properly used across the whole project.

We need to refactor so, changing the database schema will not break it all.

**Comment by bmtcril** [comment]
We should at least confirm we can change all of the databases and things still work: `ASPECTS_XAPI_DATABASE`, `ASPECTS_EVENT_SINK_DATABASE`, `ASPECTS_VECTOR_DATABASE`. What do you think about making the table names and mv names hard coded? I'm having trouble seeing a use case for changing them and it's a lot of configuration to carry around. What do you think @SoryRawyer ?

**Comment by Ian2012** [comment]
I see just one use case to override the database name, and it's just for developing purposes. Not sure what a table name override can offer that cannot be accomplished with other extensions

**Comment by bmtcril** [comment]
(and I definitely use the database changing behavior in dev and testing a fair amount, I think it's very valuable to support)

**Comment by Ian2012** [comment]
As per my testing, this is already working!
