### ISSUE TITLE
Improve duplicate event handling in Vector

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#127]
When using Vector, no checks are made to deduplicate event ids. On event replay especially this can be an issue, where a high quantity of duplicate events may land in a short period of time. A possible suggestion is to use [ReplacingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree) instead or MergeTree for the top level table type. More information is available [here](https://altinity.com/blog/clickhouse-replacingmergetree-explained-the-good-the-bad-and-the-ugly).

**Comment by Ian2012** [comment]
Didn't Clickhouse hate updates?

Can we add a constraint for unique event ids?

Is there another solution we can explore?

**Comment by bmtcril** [comment]
Yes, using the ReplacingMergeTree table type for the xapi events as mentioned above. :) My concern there is that it may / probably doesn't update the downstream materialized views, so we'd have to look into that. Alternatively we can try to do some kind of event id checking on Vector insert like Ralph does, but I'm not sure how complicated we can make SQL in Vector.

**Comment by Ian2012** [comment]
Clickhouse docs:

> Thus, ReplacingMergeTree is suitable for clearing out duplicate data in the background in order to save space, but it does not guarantee the absence of duplicates.
