### ISSUE TITLE
Backfill course data in clickhouse event sink at initialization

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#135]
When bootstrapping the Aspects project, the course data is not available unless authors update their course content.

We need to backfill the data at startup in a performant/customizable way

**Comment by Ian2012** [comment]
We can keep it optional, run it as a background job and inform users about it. It has to explore all the nodes for a course, right?

I also notice that the filters are cached for too long.

**Comment by bmtcril** [comment]
Which filters? And yeah it courseoverviews then does a full `modulestore.get_items()` to serialize out the things we want from each block.
