### ISSUE TITLE
Investigation: Aspects roles and uses cases

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#178]
This is a placeholder issue to raise the discussion around Aspects uses cases around roles.

### Current:

- Admin: equivalent to the openedx super users, those users have unlimited access to superset.
- Operator: this is a role with access to Aspects operations metrics such as last xapi received event, total synchronized courses, total organizations, current active users, events per second, etc. 
- Instructor: equivalent to the openedx instructors, those have only access to the dashboards associated with the instructor role and can see only data for the courses they have access to.

### Ideas (not implemented yet):
- Org-wide instructor: Instructors with permission to a whole organization.
- Data science: People with access to create dashboards, charts, and datasets.
- Business: People interested in sell courses
- Marketing: ??
- DevOps: People interested in the data from their deployments

Ideas are welcome too

**Comment by bmtcril** [comment]
There is a big conversation happening around roles in the LMS that I've been monitoring, but I think will inform how any of this can be implemented. I would definitely prefer not having manual management or roles and management in Superset if it's something we can get for free from the LMS in the near term.

**Comment by Ian2012** [comment]
Closing this as there is already a Product perspective.
