### ISSUE TITLE
Query for sink courses unique

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#189]
This chart doesn't show the correct information as the count is counting duplicated items

![image](https://github.com/openedx/tutor-contrib-aspects/assets/33465240/07044195-b2d4-4c89-9c93-58957728493a)

**Comment by bmtcril** [comment]
Yeah I'd spoken to Rory about this, it manifests in a few places. Thanks for making an issue for it.

**Comment by bmtcril** [comment]
Fixes for this are happening in #193 and #194

**Comment by Ian2012** [comment]
@bmtcril could you confirm whether this has been fixed?

**Comment by bmtcril** [comment]
@SoryRawyer I think we have tackled all of the cases where there was fan out due to there being multiple rows for courses and block in the event sink database, does that sound right to you?

**Comment by SoryRawyer** [comment]
@bmtcril I'm still working on a PR to update the dataset joins to use the new dictionary-backed tables, but I think that's the last piece of this.

**Comment by SoryRawyer** [comment]
Hey @Ian2012 now that #234 is merged, would you be able to refresh your Superset instance and check if this duplication is still happening?

**Comment by bmtcril** [comment]
This is actually in the operator dashboard, and the query is just making the wrong assumption about how the table is structure. It should be changed over to use `event_sink.course_names_dict` which should be deduplicated by course run and also stored in memory for faster access. I'll take a look.
