### ISSUE TITLE
Build: Investigate build issues with Superset migration 

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#228]
We're getting relatively frequent build failures in dev and (less frequently) local due to a flaky issue with a Superset migration. We should take some time to see if we can work around this, possibly with a Superset version bump, because it messes up a substantial number of PR tests.

**Comment by Ian2012** [comment]
Has been a while since I've seen this issue in CI. Specially since the upgrade to 2.1 and 3.0. 

@bmtcril can we close it?

**Comment by bmtcril** [comment]
Sounds good!
