### ISSUE TITLE
Missing Superset Translations

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#235]
It looks like there are a number of untranslated places in Superset that we may want to tackle. Their docs for translating are here: https://superset.apache.org/docs/contributing/translations/ and we may need to override their files in the plugin if we translate things they don't accept upstream. It's also possible that there are strings that are not set up in the code to be translated, which we should file bugs or PRs for. 

Navigation:
- Top left navigation ("Dashboards", "Charts", "SQL Lab", "Data")
- Top left "SQL Lab" dropdown ("SQL Editor", "Saved Queries", "Query History")
- Top left "Data" dropdown ("Databases", "Datasets")

Common Dashboard Page:
- Left side filters ("+ ADD/EDIT FILTERS", "No filter", "1 option", "12 options", "APPLY FILTERS", "CLEAR ALL")
- Left side "Filters out of scope (6)" in instructor dash
- Left side time filter drop down ("Original Value", "Minute", "Hour"...)
- "EDIT DASHBOARD" button
- "..." button items ("Enter fullscreen", "Share" and sub-items, "Set up an email report")

![Screenshot 2023-08-01 at 2 12 36 PM](https://github.com/openedx/tutor-contrib-aspects/assets/112640379/29e87328-0c26-411e-9c03-25e2ee6ddec1)

Charts Page:
- "Select or type a value" in filter selection boxes
- Visualization names ("Bar Chart", "Pie Chart", "Time-series Bar Chart v2", etc)

**Comment by Ian2012** [comment]
@bmtcril does the upgrades (superset 2.1 and 3.0) improved this? Can this be closed then?

**Comment by bmtcril** [comment]
I haven't checked though they did say translations were improved they didn't list specficially, feel free to take a look if you get to it before I do
