### ISSUE TITLE
Bug: Operator dashboard Unique actors filters out current day

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#244]
The unique actors report has a default filter that eliminates data from the current day, causing the results to be incorrect. Other reports don't seem to have this filter unless it's set at the dashboard level:

```
SELECT count(DISTINCT `actor_id`) AS `COUNT_DISTINCT(actor_id)`
FROM `xapi`.`xapi_events_all_parsed`
WHERE `emission_time` >= '2023-07-02 00:00:00'
  AND `emission_time` < '2023-08-02 00:00:00'
  AND (1 = 1)
LIMIT 100000;
```

We should either eliminate the default filter or change it to include the current day.

**Comment by Ian2012** [comment]
Remove it is the right approach
