### ISSUE TITLE
Bug: Instructor dashboard enrollments exclude current day

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#246]
Currently the default instructor dashboard filter is for the last month, but it ends that month at midnight of the current day:

```
SELECT toStartOfDay(toDateTime(`enrollment_status_date`)) AS `__timestamp`,
       count(*) AS `count`
FROM
...
WHERE `enrollment_status_date` >= '2023-08-01'
  AND `enrollment_status_date` < '2023-08-03'
  AND `org` IN ('UMONTREAL')
  AND `enrollment_status` = 'registered'
GROUP BY toStartOfDay(toDateTime(`enrollment_status_date`))
LIMIT 100000;
```

This is going to be confusing to instructors and cause a lot of issues on launch day of their course, when they most want to watch enrollments. We should find a way to make this inclusive in the same way that the other enrollment charts are.

**Comment by SoryRawyer** [comment]
I think we can address this by using a "custom" time filter and setting the end of the window to one day after the current time. Does it make sense to leave the time frame start date as 1 month ago, or is there a better default value?

**Comment by bmtcril** [comment]
That makes sense to me
