### ISSUE TITLE
Bug: Superset first sign-in hangs on instructor dashboard

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#247]
When a user (instructor or admin) first signs into Superset then clicks into the Instructor Dashboard, the charts all spin and the filters don't populate. They appear after a refresh. I assume this is a timing issue that has to do with getting permissions from LMS, but we should look into fixing it if we can.

**Comment by Ian2012** [comment]
BTW, I did find that if you click the filters suddenly the dashboard load

**Comment by SoryRawyer** [comment]
Apparently this is fixed in Superset 2.1.0: https://github.com/apache/superset/pull/23299
Do we know of anything preventing us from upgrading to 2.1.0?

**Comment by SoryRawyer** [comment]
Conversely, we could drop the requirement for a problem or video name to be selected for those component-level tabs.

**Comment by bmtcril** [comment]
I think @Ian2012 looked into 2.1, but we're also very close to a 3.0.0 which might be worth just biting the bullet and jumping to if it's not terrible. I can create a task to investigate once Apache approves a 3.0 RC, which should be any time now.
