### ISSUE TITLE
What kind of testing should be implemented on this plugin and related ones?

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#25]
## Description

Should we have unit testing or rendering testing or not having like most of the tutor plugins?

Rendering testing: https://github.com/openedx/tutor-contrib-coursegraph/blob/master/tests/test-install.sh

**Comment by bmtcril** [comment]
I'd like for there to be some small amount of testing, but most of the official plugins don't have tests that I can see (ecommerce, discovery, forums, etc). I'll ask around and see what people think is most useful.

**Comment by Ian2012** [comment]
For python files stored in `templates` that are rendered we can establish a similar workflow like this one: https://github.com/openedx/tutor-contrib-coursegraph/blob/master/tests/test-install.sh and run all tests (black, codestyle, etc) for that

**Comment by bmtcril** [comment]
Sure we could give that a try here and see how it works
