### ISSUE TITLE
StatefulSet for Vector

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#275]
As mentioned here https://github.com/openedx/tutor-contrib-aspects/issues/180#issuecomment-1658651525 it's essential to have a persistence layer on top of Vector so that logs are sent twice nor missed.

A stateful set is the right approach for that as implemented with the Aggregator Role in the vector helm chart:

https://github.com/vectordotdev/helm-charts/blob/e069a13d0931aabe6381b1a99f6a943a4a6efa75/charts/vector/templates/statefulset.yaml#L3

**Comment by Ian2012** [comment]
Seems like a statefulSet cannot be used https://stackoverflow.com/questions/55165517/handling-persistentvolumeclaim-in-daemonset#:~:text=If%20you%20use%20a%20persistentVolumeClaim,the%20storage%20using%20one%20PVC.

**Comment by bmtcril** [comment]
@Ian2012 this was fixed in #409 right?

**Comment by Ian2012** [comment]
Yes, it was
