### ISSUE TITLE
feat: add more information for course_blocks

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#292]
Useful information for course_blocks are:

- is_gradeable
- type

**Comment by bmtcril** [comment]
Type is available in the xblock_data_json, but we should definitely add gradeable if that's a thing on the block. Currently the json data looks like this:

`{"course": "GPT101", "run": "2023_02", "block_type": "vertical", "detached": 0}`

**Comment by Ian2012** [comment]
@SoryRawyer can this one be closed?

**Comment by SoryRawyer** [comment]
I think so! We should now have `graded` in the course block json, so this can be closed.
