### ISSUE TITLE
Build: investigate generating dbt project documentation during builds

### ISSUE THREAD

**Issue by SoryRawyer** [openedx/tutor-contrib-aspects#342]
As the project continues to grow, I think it would be useful to build the [dbt project documentation](https://docs.getdbt.com/docs/collaborate/documentation) during builds.

Additionally, if we add Superset entities as [exposures](https://docs.getdbt.com/docs/build/exposures), this documentation could improve discoverability of new charts and datasets and would allow stakeholders to research questions of data provenance without going through the project code.

Here are some questions I think should be considered before adding a build step to generate documentation:
- The `dbt docs generate` command writes documentation as HTML. Once the documentation is built, how is it going to be served?
- How can we programmatically add Superset assets such that the documentation always stays in sync with what's available in Superset?

**Comment by bmtcril** [comment]
Closed by https://github.com/openedx/aspects-dbt/pull/31
