### ISSUE TITLE
Bug: When running tutor initialization for this plugin I receive an error with port 9000 already in use.

### ISSUE THREAD

**Issue by ztraboo** [openedx/tutor-contrib-aspects#348]
I noticed that I was receiving the following error when running `tutor dev init --limit` aspects.

**Error 0.0.0.0:9000: bind: address already in use**
```
  ⠋ Container tutor_nutmeg_dev-clickhouse-1  Starting                                                                                                                                                   0.1s
Error response from daemon: driver failed programming external connectivity on endpoint tutor_nutmeg_dev-clickhouse-1 (056f04d95199cef94e3547958160276a6a11e50a1dbddc9028e28a16ae81de28): listen tcp4 **0.0.0.0:9000: bind: address already in use**
Error: Command failed with status 1: docker-compose -f /Users/ztraboo/Dev/EducateWorkforce/Repos/open-edx/tutor.dev.nutmeg/tutor-env/env/local/docker-compose.yml -f /Users/ztraboo/Dev/EducateWorkforce/Repos/open-edx/tutor.dev.nutmeg/tutor-env/env/dev/docker-compose.yml -f /Users/ztraboo/Dev/EducateWorkforce/Repos/open-edx/tutor.dev.nutmeg/tutor-env/env/dev/docker-compose.tmp.yml -f /Users/ztraboo/Dev/EducateWorkforce/Repos/open-edx/tutor.dev.nutmeg/tutor-env/env/dev/docker-compose.override.yml --project-name tutor_nutmeg_dev -f /Users/ztraboo/Dev/EducateWorkforce/Repos/open-edx/tutor.dev.nutmeg/tutor-env/env/local/docker-compose.jobs.yml -f /Users/ztraboo/Dev/EducateWorkforce/Repos/open-edx/tutor.dev.nutmeg/tutor-env/env/dev/docker-compose.jobs.yml -f /Users/ztraboo/Dev/EducateWorkforce/Repos/open-edx/tutor.dev.nutmeg/tutor-env/env/dev/docker-compose.jobs.tmp.yml run --rm clickhouse-job sh -e -c echo “Initialising Clickhouse...”
```

After further investigation it appears that this port 9000 conflicts with my existing `tutor-minio` container. It looks like this port mapping is just for the tutor-dev environment. I'm working with nutmeg, however, I noticed that this minio port configuration was also present in v16.0.0 (palm)
https://github.com/overhangio/tutor-minio/blob/v14.0.0/tutorminio/patches/local-docker-compose-dev-services#L3-L4

![image](https://github.com/openedx/tutor-contrib-aspects/assets/5641338/7aa07319-7f08-4cdd-8b7d-f1f7a32f2fd5)

**Comment by bmtcril** [comment]
I see, since we usually test in `local` due to the performance issues in `dev` we haven't run across it. Both plugins hard code the host port, so we'll have to make a change in ours to allow it to be configurable. Thanks for pointing it out!

**Comment by ztraboo** [comment]
@bmtcril Is it okay to test in `dev` environment for now?

**Comment by bmtcril** [comment]
@ztraboo for sure, we'd welcome any issues you run across. I think the minio fix is easy (using the same configurable ClickHouse host port as we use for the internal port so people can choose what works for them, then changing the default to something that doesn't collide with minio), just need a minute to get to it. Testing it will take longer than anything else.
