### ISSUE TITLE
Bug: Instructor Dash - Video drilldown - Video name filter

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#354]
It seems like when looking at the Video drilldown "Video name" filter the video names aren't restricted to the selected org / course name / course run as expected. I don't see anything wrong in the settings off hand, but it's possibly related to the required value / select first filter value by default settings.

**Comment by bmtcril** [comment]
@SoryRawyer I ran into this today on the beta server, set up like this:

- Demo course imported
- GPT course imported
- Demo course published
- GPT course published
- Sign into Superset as admin, go to instructor dash -> Video drilldown

Bug:
- Default "Org" filter: UMONTREAL
- Default "Video name" filter: "A Shared Culture"

Those two things shouldn't be able to coexist.

**Comment by bmtcril** [comment]
Random other context 

- No videos from the GPT course showed up in the "Video name" filter, even after I re-published the course
- Once I saved edited / saved the filter (making no changes) the GPT videos showed up in addition to the "A Shared Culture" video (but no other videos from the other course)
- Once I cleared all filters and re-selected the UMONTREAL org the correct list of videos showed up 🤷 

I'm guessing this is a Superset bug of some variety, or maybe an oddity in one of the filter tables, but if there's anything we can do to not show videos from the wrong courses that would be great

**Comment by bmtcril** [comment]
Same is happening on the problem performance tab...

![Screenshot 2023-09-07 at 4 05 48 PM](https://github.com/openedx/tutor-contrib-aspects/assets/112640379/515540fe-d3d5-4323-a4e9-fc3188419145)

**Comment by SoryRawyer** [comment]
I think you're right that this has to do with the "select first filter value by default" setting. I disabled that for the problem name filter but left the video name filter as-is and when I refreshed the dashboard I could see "A shared culture" under videos but only saw UMONTREAL problem names in the problem performance tab.

It looks like this was already reported: https://github.com/apache/superset/issues/22979

I think our only option for now is to allow those filters to be empty. I'll look into whether we can restrict the dashboard from loading until a value is picked for that filter, but I haven't come across a standard setting for that yet.

**Comment by SoryRawyer** [comment]
It appears that this also affects switching between orgs. For example, I had the UMONTREAL org selected along with one of the problem names, but when I changed the filter org to edx the problem name didn't clear. Once I picked a different problem, however, the UMONTREAL problem was no longer selected.

I have not tested this as a user that could only see one org, so it's possible that our filter datasets could still limit what's shown to just the entities a user has access to. Either way, it seems like this is a Superset bug that's still open.

**Comment by SoryRawyer** [comment]
I have a proposal: we can limit the data returned by the datasets powering the problem and video drilldown charts by adjusting the way those datasets leverage the dashboard filters. If no filter values are provided, we could default to filtering on a false condition. This would allow us to remove the default filter value without returning a lot of data that could be confusing to users.

What do you all think @bmtcril @Ian2012 ?

**Comment by Ian2012** [comment]
That's tricky but I don't why it wouldn't work. We are already making transformations to the queries based on trickier filters

**Comment by bmtcril** [comment]
That's better than what I was thinking, if it's not a ton of work I'd like to give it a shot.

**Comment by SoryRawyer** [comment]
I think #377 addressed this. Could this be closed?

**Comment by bmtcril** [comment]
Yep, all set
