### ISSUE TITLE
Implement translations for Superset assets

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#36]
Superset has some amount of translation built in, but I haven't found much documentation about it. I think we need to add some capability into the OARS plugin itself to translate the dashboard and chart names if nothing else. We should be able to do this using the typical openedx translations project to get files in, but will probably have to find a way to roll our own project for doing the replacement at Tutor build time, and it will probably only support 1 language per install unless I misunderstand how Superset naming works.

**Comment by Ian2012** [comment]
As far as I know there is no support for dashboard translation: https://github.com/apache/superset/issues/13030

**Comment by bmtcril** [comment]
Yes, this would be something that we would implement at the OARS level that would translate the names as part of the Tutor jinja replacement, before they are created in Superset

**Comment by Ian2012** [comment]
I had an idea that I'm exploring:

- Get the user language from a cookie, API call, or whatever. Important to be tied to the open edx platform.
- At the authentication level assign two basic roles: `Open edX` which has minimal permissions and `Open edX - {language}` which has access to the translated dashboards for the given dashboards.
- At the import level per a given asset (dashboard/charts) and a language, generate the assets with the corresponding translations.

This should be implemented for the course staff, and other roles like admins, data science, etc. would not be covered

**Comment by ielatifi** [comment]
+1 for region aware dashboards with automatic translation

**Comment by Yisel-Ulloa** [comment]
Good morning @Ian2012, @bmtcril, @ielatifi, @openback, @mtyaka. Do you know if there is already an option to be able to translate these texts dynamically?

**Comment by bmtcril** [comment]
@Yisel-Ulloa this repository is for the specific Open edX analytics plugin called Aspects. The current state of translations is in Aspects is this:

- Superset itself has some translations for the overall UI, but they are limited to 16 or so languages. Most of the strings are translatable at this point, but not all.
- Superset does not support right-to-left languages such as Arabic or Hebrew at this time 
- Aspects built-in dashboards and charts are translated into 36 languages for all of the places that we are able to translate given the limitations of Superset. Across all languages about 97% of the strings are translated, though many still need to be reviewed.
- Aspects does this localization by creating separate dashboards and charts for each locale that the Open edX instance supports and trying to match the user's LMS language in Superset. This required a great deal of custom scripting and uses Open edX specific integrations with Transifex for managing the translations.

Work is ongoing to help improve Superset translations with several Open edX contributors pushing that forward. Some examples:

- https://github.com/apache/superset/issues/32139 (which it looks like you've already commented on)
- https://github.com/apache/superset/issues/25258

Hope this helps.
