### ISSUE TITLE
Feat: grading events top-level materialized view

### ISSUE THREAD

**Issue by SoryRawyer** [openedx/tutor-contrib-aspects#360]
Some of the feedback for the instructor dashboard involved showing course grades. As a developer, it would be useful to have a top-level materialized view that contained information about learner grades at the problem and course level. As I understand it, these events are represented by the verb ID `http://id.tincanapi.com/verb/earned`. Below is a proposed schema for the view:

- event_id
- emission_time
- org
- course_key
- actor_id
- object_id
- verb_id
- scaled_score (a floating-point number between 0 and 1)

**A question about what data should be included:** The grading events seem to include grades for sequential and course blocks. Do sequential blocks have a one-to-one relationship with problem blocks? Put differently, is it sufficient to rely on grading events for sequential blocks, or should we also include the problem response events in this dataset as well?

**Comment by bmtcril** [comment]
That makes sense to me. This all set to be closed now?

**Comment by SoryRawyer** [comment]
Yup!
