### ISSUE TITLE
Feat: add grading visualizations to instructor dashboard

### ISSUE THREAD

**Issue by SoryRawyer** [openedx/tutor-contrib-aspects#368]
The instructor dashboard is missing information to answer questions related to grading, such as:
- What grade are learners averaging for specific graded assignments?
- What is the current average grade of learners in my course?
- What is the average grade of learners in all previous course runs?

To give instructors insight into learner grades, I think it would be helpful to show a histogram of grade buckets rather than a single average. For example, a certain chart might contain the number of learners with grades in the following ranges:
- \>90%
- 80-89%
- 70-79%
- <70%

Does that seem like a reasonable visualization of course/subsection/problem grades? If so, is there a specific set of grade buckets we should group by?

**Comment by Ian2012** [comment]
I think that's the perfect solution for the visualization of grades. Most people will look up only at the buckets, but I would lower the range for the buckets. Maybe something like:

Green: `>80%`
Yellow: `50%> x >80%`
Orange: `20%> x >50%`
Red: `0%> x >20%`

What do you think?

**Comment by bmtcril** [comment]
I think it makes sense, we should probably just bucket it in 10% ranges, color coding would be nice but I'm concerned that passing and failing are configurable and it might confuse instructors if the colors don't match their configuration. 

@SoryRawyer Are you thinking about having the course / section / subsection be filters and just have one chart?

**Comment by SoryRawyer** [comment]
@bmtcril I was thinking we could have one chart at the component level on the "Problem performance" tab, and maybe another at the course/subsection level on the "Course problem engagement" tab (with an additional filter for subsection). What do you think?

**Comment by SoryRawyer** [comment]
As far as how we roll up grades, I don't see any grading events for sections (which I think are represented as blocks with a block type of "chapter"). Do we want to initially display grades at the course, subsection, and problem levels, then add in sections later?

**Comment by bmtcril** [comment]
Sounds good to me 👍

**Comment by SoryRawyer** [comment]
This should have occurred to me while I was writing the above, but I don't think there's an easy way to filter the other chart on the "Course problem engagement" tab by subsection. I think it'd be awkward to have one chart respond to a subsection filter while the other doesn't, so I think there are two options:
1. Add subsection as a dimension to our data models and allow charts to be filtered that way, or
2. Only show grade distributions at the course and problem level and leave open the option for adding a subsection filter

What do you think? Is it important for us to narrow down metrics to the subsection level, or would we be fine leaving things at the course and component levels for now?

**Comment by SoryRawyer** [comment]
With the recent merging of new charts I think this can be closed. Are there any other grade visualizations that should be added at the moment?

**Comment by bmtcril** [comment]
Nope, I think this is all set for now!
