### ISSUE TITLE
Loc: Allow localization for labels that come from datasets

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#388]
As noted in #379 these types of labels are currently not able to be localized:

- Enrollments By Enrollment Mode uses the verb name in tooltip display "audit" / "verified"
- Enrollment Events Per Day uses the verb name in tooltip display "registered" / "unregistered"
- Problem Responses - displays "True" / "False" for correct / incorrect responses
- Watches Per Video - displays "Total plays" / "Unique watchers" from the metrics
- Several places where "count" appears in the tooltips, I'm not sure if we want to turn this off or try to rename it

We would like to fix this without localizing the datasets themselves, as the greatly complicates deployment. I don't have any options for this now, it will take some research to complete.

**Comment by Ian2012** [comment]
I had the idea of using a Jinja filter that receives the text and the user (to load the language settings) and returns the translated text, but the idea is not complete yet. It would be worth to explore

**Comment by bmtcril** [comment]
@Ian2012 can we consider this done now?

**Comment by Ian2012** [comment]
Yes, user facing strings from datasets are already translated.
