### ISSUE TITLE
Failed to run init command: cannot create directory ‘/app/assets/superset’: Permission denied

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/tutor-contrib-aspects#394]
Hi
Installing `aspects`, enabling the plugin, saving config and `tutor k8s do init --limit` will fail.

<img src="https://github.com/openedx/tutor-contrib-aspects/assets/49523567/4b280969-c9f6-4ebc-a8b6-928ca24eabc8" width=500/>

The reason is the User is changed to superset at the end of the Dockerfile:

https://github.com/openedx/tutor-contrib-aspects/blob/4dfc7ee735e75555906349bdc357bd5f8d86ed91/tutoraspects/templates/aspects/build/aspects-superset/Dockerfile#L39C4-L39C14

and it doesn't have permission to create the directory in the `/app` with root as the owner.

tutor version 15.3.6
aspects version: 0.42.0
OS: Ubuntu 20.04

**Comment by Ian2012** [comment]
Thanks for this report, this is already resolved by this PR:

https://github.com/openedx/tutor-contrib-aspects/pull/391

Can you test it out and provide feedback?

**Comment by bmtcril** [comment]
Hi Emad, the above PR is merged now, so you should be able to install latest to test it out.

**Comment by CodeWithEmad** [comment]
Awesome.
This is fixed in 0.42.1. Thanks.
