### ISSUE TITLE
Transcripts / Captions Per Video - en

### ISSUE THREAD

**Issue by e0d** [openedx/tutor-contrib-aspects#405]
Seeing this message on the Video Engagement tab.  Unfortunately, clicking on the message doesn't provide any additional data.

![image](https://github.com/openedx/tutor-contrib-aspects/assets/1270274/5d2c0369-db5b-4bc4-b70a-9129c7e2c055)

**Comment by Ian2012** [comment]
In the three-dot button, you can refresh the data. After you click that, is it working?

Can you provide logs for Superset and Clickhouse?

**Comment by e0d** [comment]
I'm seeing this on the beta site, so I don't have access to the logs.  I'll try refreshing and see what happens.

**Comment by bmtcril** [comment]
Marking this one as stale, we haven't seen it since the Superset 3.0 upgrade. @e0d ping the ticket if you happen to see it again and we'll keep digging.

**Comment by bmtcril** [comment]
Still haven't seen this recently, so I'm going to close it.
