### ISSUE TITLE
Feat: Superset introspection

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#427]
It's a nice to have, but it would be great to add some data around the usage of Superset itself. Some inspiration is here: https://engineering.hometogo.com/monitor-superset-usage-via-superset-c7f9fba79525 we would also like to add performance data for the queries if that can be found. That article seems skeptical.

**Comment by Ian2012** [comment]
The performance data can be loaded from the Clickhouse `system.metricts` table: https://clickhouse.com/docs/en/operations/system-tables/metrics

**Comment by pomegranited** [comment]
@Ian2012 

> The performance data can be loaded from the Clickhouse system.metrics table: https://clickhouse.com/docs/en/operations/system-tables/metrics

There's a number of metrics we can report on here -- are there any in particular that you think would be useful for operators?

**Comment by bmtcril** [comment]
I'll ask Altinity what they suggest for monitoring system health, it's hard to know off hand which are useful with there being so many. 😬

**Comment by bmtcril** [comment]
Here's a good list to work from:

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-monitoring/#build-your-own-monitoring

I think whatever we can get from there would be more than sufficient to start off.
