### ISSUE TITLE
Refactor: Revert filter workarounds

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#437]
Due to bugs in Superset 2.1 we had to change our whole filtering strategy to prevent courses and blocks from courses that instructors didn't have access to being displayed as filter choices. This should be fixed in Superset 3.0 so we should revert those changes:

- Course name should be required any place where charts won't show without it
- Problem name / Video name should be required any place where charts won't show without them
- Any places where we short circuit virtual datasets based on not having a filter chosen should be removed, it this means the virtual dataset can be moved back to dbt we should do that

https://github.com/openedx/tutor-contrib-aspects/pull/377 most changes came from this PR, so it should be a good guide for what needs to be undone.

**Comment by SoryRawyer** [comment]
Maybe this is a caching issue, but I'm still seeing incorrect values for filters when enabling "select first value by default" (e.g. seeing demo course problem names despite having the UMONTREAL org selected). Could someone else confirm if they're seeing this behavior as well?

**Comment by bmtcril** [comment]
@SoryRawyer I'm not seeing it on the beta site, either as instructor or admin. I've changed the filters in the `-en` instructor dashboard to make course name required and "select first filter value by default". Could be a data ordering issue (which course was loaded first?), but can you want to try it out on the beta site and let me know what you think?

**Comment by bmtcril** [comment]
You may also want to make sure you've got the right version of the Superset image as there were some bumps for me upgrading locally to Superset 3. The image should be around `edunext/aspects-superset:0.52.2` or so.

**Comment by SoryRawyer** [comment]
Interesting. I'm seeing the correct behavior on the beta server, however I also briefly see "2 options" under the course run filter, followed quickly by a change to "1 option". When I make course run a required filter locally, I get a non-UMONTREAL course run as the default value and a non-UMONTREAL problem/video name as the default value.

For this change, I'll leave course run as an optional filter. Does that sound reasonable?

**Comment by bmtcril** [comment]
I've configured the "-en" dashboard on the beta server to make the problem and video names required and still can't replicate the behavior, which is maddening. I'm not too worried about the quick-change while filters load, but am curious what you see now on the beta.

**Comment by SoryRawyer** [comment]
Huh, this is what I see when I look at the problem performance tab:
![Screenshot from 2023-10-12 11-05-56](https://github.com/openedx/tutor-contrib-aspects/assets/2566242/c4fd1350-8419-4662-9344-938f87babd6e)

**Comment by bmtcril** [comment]
Looks like this isn't fixed after all, we should punt on it for now. I'll mark this as stale so we don't lose it.

**Comment by bmtcril** [comment]
This is going to be obviated by changes for the v1 dashboards based on the new PRD.
