### ISSUE TITLE
Initialize the `superset` database to utf8mb4

### ISSUE THREAD

**Issue by OmarIthawi** [openedx/tutor-contrib-aspects#452]
MySQL is initialized to `latin1`.

This prevents us from adding Arabic or other Unicode.'

On the other hand `edxapp` is being created correctly:

```
CREATE DATABASE `edxapp` /*!40100 DEFAULT CHARACTER SET utf8mb4 */‏‏
```

@Ian2012 would you mind taking a look?

## Context

We're aiming to add full Arabic support for both Aspect and superset for @nelc:

   * RTL: https://github.com/apache/superset/issues/25258
   * Unicode support (this issue)
   * Translations of the Aspect dashboard UI (Needs contribution)
   * Translations for the Superset UI: https://github.com/apache/superset/issues/25258

**Comment by bmtcril** [comment]
Also we should use `utf8mb4` instead of `utf8` to get the full suite of code points!
