### ISSUE TITLE
Invalid URL in README.rst

### ISSUE THREAD

**Issue by moonesque** [openedx/tutor-contrib-aspects#484]
https://github.com/openedx/tutor-contrib-aspects/blob/fb3efbb58bffab9d4f4f07c6fd3fb8e7f24cdc03/README.rst?plain=1#L10
The plugin docs URL scheme has been repeated by mistake.
Insignificant change, but I can make the PR if I could push my branch.

**Comment by Ian2012** [comment]
Hi @moonesque, thanks for your report. For contributions you can fork this repo and push your branch to it, then you can open a PR from the fork to this repo

**Comment by bmtcril** [comment]
Hi @moonesque , we actually would need a license agreement with you to accept a PR which is some paperwork and a bit of a process. Unless you are planning to do other work in the openedx org (which we'd love!) this issue is probably the right way to go and we can take care of it.
