### ISSUE TITLE
Bug: Distribution of Responses errors

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#494]
Certain questions on the Beta server are throwing an error for the Distribution of Responses chart:

```
:HTTPDriver for http://clickhouse:8123 returned response code 400)
 Code: 26. DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '"': while executing 'FUNCTION if(startsWith(responses, '[') :: 4, CAST(responses, 'Array(String)') :: 1, array(responses) :: 3) -> if(startsWith(re
This may be triggered by: 
Issue 1002 - The database returned an unexpected error.
```

This appears to be related to the parsing of multiple answers in fact_problem_responses.sql: https://github.com/openedx/tutor-contrib-aspects/blob/4ea65d69307b53e5da96cedb46296c785fe3a259/tutoraspects/templates/openedx-assets/queries/fact_problem_responses.sql#L19

Seems to be because the answers are sometimes single quoted, sometimes double quoted:

```
 ["Un emprunt à l'anglais ou anglicisme", 'Un type de demande', 'Une question structurée et précise']                                                                
 ['Un type de demande']                                                                                                                                              │
 ['Une question structurée et précise', 'Un type de poisson']
```

**Comment by bmtcril** [comment]
@SoryRawyer heads up in case you can get to looking at this before I can...

**Comment by SoryRawyer** [comment]
Gah, sorry for missing this. I found a workaround that involves escaping single quotes and then replacing double quotes with single quotes. If you think that would be an acceptable solution, I can open a PR with that change.

**Comment by bmtcril** [comment]
Ah nice, that seems better and probably faster than the regex I was working on. A PR for that would be great. If there's a way we could bump the escaping logic up into the MV so it's only got to be processed once that would be ideal.
