### ISSUE TITLE
CilckHouse user config not working in k8s

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#558]
The overrides we do on user config are not currently possible in a k8s deployment, since we want to mount the override file as a configmap, which makes the directory read only... but ClickHouse always wants to write a file to the users directory. We might be able to get around this by making it a PVC, I don't currently see any other way to do it but haven't spent much time on it.

https://clickhouse.com/docs/en/operations/configuration-files#user-settings

**Comment by bmtcril** [comment]
@Ian2012 this was fixed here, right? https://github.com/openedx/tutor-contrib-aspects/pull/575

**Comment by Ian2012** [comment]
Yes, it was
