### ISSUE TITLE
Bug: Moving MVs to dbt caused them to be materialized to the wrong schema

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#561]
We need to fix up the dbt project so that the MVs we had in the xapi schema go back there. We should be able to do this by doing the following:

- Override the generate_schema_name macro to not concatenate custom schema names to the target schema
- Add schema to the model configs of the MVs, using an env var that points to the xapi schema, like we do here: https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh#L18C13-L18C13

It's also possible to simply override the database using the env var like we do here: https://github.com/openedx/aspects-dbt/blob/d0b59458faf368b51ad8b6d44bce75ab895e6ee8/models/completion/schema.yml#L5

More info: https://docs.getdbt.com/docs/build/custom-schemas

**Comment by bmtcril** [comment]
@SoryRawyer just giving you a heads up on this one

**Comment by SoryRawyer** [comment]
My apologies for overlooking this. As far as I know, the MVs and tables that should go into the `ASPECTS_XAPI_DATABASE` schema are listed here: https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/plugin.py#L81-L97
Am I forgetting anything?

**Comment by bmtcril** [comment]
@SoryRawyer seems right to me

**Comment by bmtcril** [comment]
Fixed by:
https://github.com/openedx/aspects-dbt/pull/39
https://github.com/openedx/tutor-contrib-aspects/pull/562
