### ISSUE TITLE
Upgrade Superset to v4.x

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#618]
In an effort to stay as close as possible to the latest supported version, we should upgrade to the latest v4.x available at the end of March. This should allow us sufficient time to find any blocking issues or adopt new features. 

I have run basic testing for the v4.0.0rc1 and was able to successfully init and see all charts without error (though not all charts had data to confirm functionality). This is pretty heartening, and we've had good luck with Superset upgrades so far, so we have good reason to think this shouldn't be a large task.

**Comment by Ian2012** [comment]
Closed on: https://github.com/openedx/tutor-contrib-aspects/pull/693
