### ISSUE TITLE
Sort locale yaml recursively

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#749]
Currently, PRs that update the localization only sort on the top level map (the language key). When we get locale updates the diffs are a mess because the internal keys (the string being translated) are unordered and move around each time. We should take the time to implement something like this so we can see what's actually changing and make sure nothing seems off: https://stackoverflow.com/questions/51386822/how-to-recursively-sort-yaml-using-commentedmap

This would go in `translate_utils.py::compile_translations` before we dump the yaml.

**Comment by Ian2012** [comment]
This should apply to the assets serialization too

**Comment by bmtcril** [comment]
Fixed in #764
