### ISSUE TITLE
Possible token refresh issue in embedded dashboards

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#759]
I've run into an issue once on the beta server where embedded Superset dashboards got into a bad token state. This issue is to track it if it comes up again. I haven't been able to reproduce it since. Here's what I think may have happened:

- Navigated to embedded dashboard, navigated between pages
- Stopped to talk for a few minutes
- May have navigated to Superset proper to look at other dashboards?
- ~5 mins after initial load [this error](https://github.com/apache/superset/blob/9ffcd6410eb39c2cc911707e1b264df4a1b74a8c/superset-frontend/src/embedded/index.tsx#L144) started showing, and no amount of refreshing would make it go away for another 5 mins or so
- Suddenly started working again

**Comment by Ian2012** [comment]
Superset guest tokens use the same cookie as the default Superset cookie for authentication. The problem may be that you shouldn't have two Superset sessions (in browser, in iframe) at the same time, it may cause conflicts.

This is just based on my understanding of Superset, it needs to be confirmed first.

**Comment by bmtcril** [comment]
I was just able to reproduce, here are the Superset logs:

```
superset-1  | 69.207.83.88 - - [08/May/2024:19:30:52 +0000] "GET /api/v1/me/roles/ HTTP/1.1" 401 29 "https://superset.aspects-beta.openedx.org/embedded/257f514e-f480-5035-86c4-10540b48d267?uiConfig=3&expand_filters=false" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0"
superset-1  | 2024-05-08 19:30:52,082:WARNING:superset.security.manager:Invalid guest token
superset-1  | Traceback (most recent call last):
superset-1  |   File "/app/superset/security/manager.py", line 2338, in get_guest_user_from_request
superset-1  |     token = self.parse_jwt_guest_token(raw_token)
superset-1  |   File "/app/superset/security/manager.py", line 2370, in parse_jwt_guest_token
superset-1  |     return self.pyjwt_for_guest_token.decode(
superset-1  |   File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 129, in decode
superset-1  |     decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
superset-1  |   File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 116, in decode_complete
superset-1  |     self._validate_claims(payload, merged_options, **kwargs)
superset-1  |   File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 152, in _validate_claims
superset-1  |     self._validate_exp(payload, now, leeway)
superset-1  |   File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 187, in _validate_exp
superset-1  |     raise ExpiredSignatureError("Signature has expired")
superset-1  | jwt.exceptions.ExpiredSignatureError: Signature has expired
```
