### ISSUE TITLE
Allow custom dbt packages & overrides

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#76]
Once #70 merges we should look into how best to add or replace dbt packages. Right now we use the project's: https://github.com/openedx/oars-dbt/blob/main/oars/packages.yml but will want to make that configurable so that operators can add their own custom dbt packages built on top of ours. Doing so may require newer / different versions of packages we use, so it's important they be able to override those as well. This should just be a case of writing a yml file to the right place when running the dbt commands.

**Comment by Ian2012** [comment]
If the way to extend DBT is to fork the project, I guess users can just add their own packages to the file.

Is my understanding correct?

If it's, this issue is not needed

**Comment by bmtcril** [comment]
There's no need to fork the project to extend it, that's what dbt packages do: https://docs.getdbt.com/docs/build/packages If you want to override the default models for some reason that might require a fork.

**Comment by Ian2012** [comment]
Solved here https://github.com/openedx/tutor-contrib-aspects/pull/138
