### ISSUE TITLE
Unlocalized dataset colum names appear as "None"

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#760]
In the "Course Information" chart on the Course Dashboard, the org/course/course name labels show up as None. We should be able to default these to their regular labels as we do with other missing translations.

![Screenshot 2024-05-03 at 11 12 22 AM](https://github.com/openedx/tutor-contrib-aspects/assets/112640379/64fca4c7-fe3d-4f4b-94c3-c1c69aa6ff18)

**Comment by Ian2012** [comment]
I was thinking on adding checks for it previous to the serialization of them

**Comment by Ian2012** [comment]
No, it's a matter of setting `verbose_name` for every dataset column
