### ISSUE TITLE
[BUG] Problem installing Aspects in previous versions

### ISSUE THREAD

**Issue by MaferMazu** [openedx/tutor-contrib-aspects#777]
## Description
When I tried to install this plugin in its latest version in Palm or Olive, I got the following error:
`ModuleNotFoundError: No module named 'importlib_resources'`
I know you added the requirement to the base.in file https://github.com/openedx/tutor-contrib-aspects/commit/ad2c1951d87aafc24a617a43c2123470bec0b3e4, but I think you are not using that `base.in` in the installation process. In your setup.py, you only have as requirements tutor and bcrypt https://github.com/openedx/tutor-contrib-aspects/blob/main/setup.py#L48

Note: I can only install Aspects v0.73.1 or lower in those releases.

## Suggestion
We probably want to add the `base.in` as an install requirement. Example: https://github.com/openedx/openedx-events/blob/main/setup.py#L150

## Expected behavior
Be able to install Aspects in previous versions of Open edX (more specific tutor versions < 17.0.2)

**Comment by MaferMazu** [comment]
cc @Ian2012 @bmtcril

**Comment by bmtcril** [comment]
Got it, thank you! I'll try to walk through the install process on Nutmeg and up tomorrow.

**Comment by bmtcril** [comment]
I'm not able to go all the way back to Nutmeg, but in Olive I'm also getting this due to `xblockutils` being deprecated and these calls moving to `xblock.utils`.

```
2024-05-08 14:43:26,617 WARNING 12 [xblock.plugin] [user None] [ip None] plugin.py:144 - Unable to load XBlock 'superset'
Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/xblock/plugin.py", line 141, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/openedx/venv/lib/python3.8/site-packages/xblock/plugin.py", line 70, in _load_class_entry_point
    class_ = entry_point.load()
  File "/openedx/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/openedx/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/openedx/venv/lib/python3.8/site-packages/platform_plugin_aspects/xblock.py", line 16, in <module>
    from xblock.utils.resources import ResourceLoader
ModuleNotFoundError: No module named 'xblock.utils'
```

**Comment by Ian2012** [comment]
This can be fixed like it was in fedbackXBlock: https://github.com/openedx/FeedbackXBlock/blob/4879ab5fdd139ee90494889541eaf43d731347a1/feedback/feedback.py#L18-L21

**Comment by MaferMazu** [comment]
Thanks a lot for the fix; it was faster than I expected 🙌 Thanks.
