### ISSUE TITLE
Bug: % correct and % incorrect problem attempts showing up as decimals

### ISSUE THREAD

**Issue by crathbun428** [openedx/tutor-contrib-aspects#793]
Steps to Reproduce
1. Navigate to the Engagement/Problems tab on the Course Dashboard, Individual Learner Reports, and At-Risk Learner Reports
2. View the % correct and % incorrect columns in the Problem Results table

Expected Results
1. The data in these columns show up as percentages

Actual Results
1. The data in these columns show up as decimals, see below:
![Screenshot 2024-05-09 at 3 59 08 PM](https://github.com/openedx/tutor-contrib-aspects/assets/57507106/aeadc02e-a842-40b7-a8c2-17a97de556a1)

**Comment by crathbun428** [comment]
@Ian2012 - This appears to be done, correct? If so - I can close it out. 

cc: @bmtcril

**Comment by bmtcril** [comment]
The last fixes should be in #822 , so I can close this when that merges
