### ISSUE TITLE
Update Watched video segments chart to show video segment timestamp ranges

### ISSUE THREAD

**Issue by crathbun428** [openedx/tutor-contrib-aspects#795]
Steps to Reproduce:
1. Navigate to the Engagement/Problems tab on the Course Dashboard, Individual Learner Reports, and At-Risk Learner Reports
2. View the Watched Video Segments graph on the Engagement/Videos tab on the Course Dashboard and the At-Risk Learner Reports; and the Videos tab on the Individual Learner Reports

Expected Results:
1. Each bar is labeled with the 5 second timestamp range of the video segment (Examples: 5-9, 10-14, 15-19, 20-24): 
Note: These video segment timestamp ranges should be shown in order. 

Actual Results: 
1. Each bar is labeled with one integer, the beginning of the 5 second video timestamp range (Examples: 5, 10, 15, 20): 
![Screenshot 2024-05-09 at 4 57 06 PM](https://github.com/openedx/tutor-contrib-aspects/assets/57507106/d85b197b-bcdf-4a4f-a421-bf1b45476579)

**Comment by bmtcril** [comment]
#791 should fix the labels, I think the ranges are still WIP

**Comment by crathbun428** [comment]
I'll update this ticket now to remove the labels bit.
