### ISSUE TITLE
Investigate Caddy configuration

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#796]
It's likely that we can improve overall performance by having Caddy use http/2 for Superset and Ralph, we should dig further into other optimizations we can make at this level.

**Comment by bmtcril** [comment]
@Ian2012 this was fixed here, right? https://github.com/openedx/tutor-contrib-aspects/pull/803

**Comment by Ian2012** [comment]
Yes, connections aren't closed anymore and Caddy defaults to HTTP/2
