### ISSUE TITLE
Perf: Individual Learner dashboard issues

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#799]
Tested with the 300M row dataset on ClickHouse Cloud I've found the following issues:

OOM:

- Problem Results
- Watched Video Segments
- Partial and full views per video
- Partial and full views per video (table)

Slow Queries (> 3 seconds):

- Learner Summary (100 rows, 23 seconds)
- Problems attempted per section/subsection (43 rows, 5 seconds)
- Problems attempted per section (9 rows, 4 seconds)
- Problems attempted per subsection (34 rows, 4 seconds)
- Video views per section/subsection (24 rows, 4 seconds)
- Video views per section (7 rows, 4 seconds)
- Page views per section (7 rows, 4 seconds)
- Video views per subsection (17 rows, 4 seconds)
- Page views per subsection (30 rows, 3 seconds)
- Page views per section/subsection (37 rows, 3 seconds)

**Comment by bmtcril** [comment]
Fixes for everything but problem interactions and problem results are here https://github.com/openedx/tutor-contrib-aspects/pull/812

**Comment by crathbun428** [comment]
@bmtcril - I see the linked issue was merged. Does this mean we should close/mark this as done? Or is any of this work still being done.

**Comment by bmtcril** [comment]
I think we can close these, we need to do another round of testing now that we have finalized the dashboards and can create new issues if need be.
