### ISSUE TITLE
Perf: Course dashboard performance issues

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#800]
Tested with the 300M row dataset on ClickHouse Cloud I've found the following issues:

OOM Errors:

- Problem Results
- Problem Interactions
- Watched Video Segments
- Partial and full views per video

Slow Queries (> 3 seconds):

- Problems attempted per section/subsection (43 rows, 5 seconds)
- Video views per section/subsection (24 rows, 4 seconds)
- Page views per section/subsection (37 rows, 3 seconds)

**Comment by SoryRawyer** [comment]
I have been trying to make changes to `int_problem_results` in dbt, but so far the best results have been when I could filter the subqueries individually. This suggests to me that we should move `int_problem_results` into Superset and rely on templating to make sure queries make proper use of indexes.

I will look into a similar approach for the watched video segments query.

**Comment by Ian2012** [comment]
@SoryRawyer I think I can move this dataset to a MV with MergeEngine: https://github.com/openedx/aspects-dbt/blob/b16a7957de4506e22768cb4a610798113c9868a2/models/problems/int_problem_results.sql#L4

Would that also be a suitable solution? cc @bmtcril

**Comment by bmtcril** [comment]
Problems with everything but problem interactions and problem results are here https://github.com/openedx/tutor-contrib-aspects/pull/808

**Comment by Ian2012** [comment]
fixes for problem interactions - problem results are here: https://github.com/openedx/tutor-contrib-aspects/pull/825

**Comment by bmtcril** [comment]
I believe these issues are all fixed now!
