### ISSUE TITLE
Extract additional dashboard strings for translation

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#840]
Currently we are missing some strings from Dashboard translations:

- `chart.meta.sliceNameOverride`

We should be able to test this by running `make extract_translations` to debug and make sure the strings get picked up correctly.

**Comment by Ian2012** [comment]
I don't think `"position.*.meta.code"` would work as that's not rendered. We should add that to other yaml and load it like we do for `dataset_strings`

**Comment by Ian2012** [comment]
The following things would also need translation:

- Charts.params.groupby.label
- Dashboards.position.*.meta.sliceNameOverride

This would require:
- allowing the extracting script to fetch those values
- once those are in place, inject it on the translated assets
