### ISSUE TITLE
Hardcoded databases names break Aspects

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#909]
### Description

Some database references are hard coded on the templates for datasets:
- https://github.com/openedx/tutor-contrib-aspects/blob/24f4a8feb59946db6112b5aa3ba2f1d58cf4f888/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/enrollment_status.yaml#L151
- https://github.com/openedx/tutor-contrib-aspects/blob/24f4a8feb59946db6112b5aa3ba2f1d58cf4f888/tutoraspects/templates/openedx-assets/queries/int_problem_results.sql#L88

This makes us unable to change the database names for multi-installation environments:

![image](https://github.com/user-attachments/assets/4fcef5fc-7128-4263-9254-fe6a2822250b)

We could take this opportunity to improve the developer experience and do a deeper analysis of SQL queries

**Comment by bmtcril** [comment]
It's an ugly temporary solution, but you can work around this by updating the sql in the UI, correct?

**Comment by Ian2012** [comment]
Yes, but you need to do it for every locale
