### ISSUE TITLE
Add 'Help' tab to Course Comparison Dashboard

### ISSUE THREAD

**Issue by saraburns1** [openedx/tutor-contrib-aspects#944]
Same help tab as in Course Dashboard. Link to blank documentation page

**Comment by bmtcril** [comment]
@saraburns1  This is for the new course comparison dashboard, right?

**Comment by saraburns1** [comment]
Yes sorry, should have specified that

**Comment by daniriosp** [comment]
This is, you jst need to copy and paste

## Help<br>* [Aspects Reference](https://docs.openedx.org/projects/openedx-aspects/page/reference/course_overview_dashboard.html)<br>* [Superset Resources](https://github.com/apache/superset#resources)<br>

**Comment by saraburns1** [comment]
@daniriosp - here is the new documentation link you can use 

https://docs.openedx.org/projects/openedx-aspects/en/latest/reference/course_comparison_dashboard.html

**Comment by saraburns1** [comment]
wait I don't think this is done. @crathbun428 wasn't @daniriosp going to do this?

**Comment by daniriosp** [comment]
Hi @saraburns1 

@Ian2012 shared with me this link:

https://superset.axim.atlas.edunext.link/superset/dashboard/course-comparison/?native_filters_key=fkoH4Iz7J85OJ-9GbcT5e0wXzt3l4NqSt8MXbSMHeFbVgpklxQ8o5P6qh47ZwOWP

and as you can see. I already created the help tab and update the link for this link
https://docs.openedx.org/projects/openedx-aspects/en/latest/reference/course_comparison_dashboard.html

![image](https://github.com/user-attachments/assets/4e3950a1-5ac2-4b2c-97df-972ce5f80d86)
